# Generated by Django 4.2.16 on 2024-10-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='items',
        ),
        migrations.AddField(
            model_name='receipt',
            name='items',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
