# Generated by Django 4.2.16 on 2024-10-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_alter_receipt_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='receipt',
            name='total',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
